// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqgdrnubsfilughubxbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxZ2RybnVic2ZpbHVnaHVieGJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDg0NDYsImV4cCI6MjA2NjMyNDQ0Nn0.n_99PMs-EiaFAOwbk8Uq0SHD3pWukJS1no4CTF-5tEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);